name: "Gosec action demo"

on: [push, pull_request]

jobs:
  gosec_analysis:
    run-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@v1
      - uses: securego/gosec@master
        with:
          args: "./"
