name: Gosec Action | Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gosec-auto-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: ./...
