name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gosec-auto-analysis:
    runs-on: ubuntu-latest
    env:
      GO101MODULE: on # Look for hardcoded credentials

    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: "./.."
